load:
  path: 'csv'
  year: '2022'
  start_year: 1901
  end_year: 2023
  period: 'hourly'
  polygon: [
          [
            [
              -77.90335456889079,
              46.075580026850844
            ],
            [
              -77.90335456889079,
              39.2376280432014
            ],
            [
              -67.86436058248752,
              39.2376280432014
            ],
            [
              -67.86436058248752,
              46.075580026850844
            ],
            [
              -77.90335456889079,
              46.075580026850844
            ]
          ]
        ]
files_workspace:
  host: hostname
  username: username
  password: password
  port: 2022
  path: path_where_csv_files_are_located

db:
  username: username_for_mysql
  password: password
  hostname: hostname
  port: 3306
  database_name: 'weather_info'




