load:
  path: 'csv'
  year: '2022'
  start_year: 1901
  end_year: 2023
  period: 'hourly'
  polygon: [
          [
            [
              -77.90335456889079,
              46.075580026850844
            ],
            [
              -77.90335456889079,
              39.2376280432014
            ],
            [
              -67.86436058248752,
              39.2376280432014
            ],
            [
              -67.86436058248752,
              46.075580026850844
            ],
            [
              -77.90335456889079,
              46.075580026850844
            ]
          ]
        ]
files_workspace:
  host: files.clarksonmsda.org
  username: kanthar@clarkson.edu
  password: Clarkson.13676
  port: 2022
  path: srv/sftpgo/data/users/kanthar@clarkson.edu/nws-hourly/csv

db:
  username: 'clarkson24'
  password: 'clark@2024'
  hostname: 'apps.clarksonmsda.org'
  port: 3306
  database_name: 'weather_info'




